create extension if not exists vector
with
  schema extensions;

-- ---------------------------------------------------------------------------
-- Per-user knowledge base
--
-- Each user uploads their own files. Files live in a private Storage bucket
-- under a folder named after the user's id ("<uid>/<filename>"), and the text
-- chunks + embeddings live in public.documents scoped by user_id. The chat
-- only ever retrieves context from the calling user's own documents.
-- ---------------------------------------------------------------------------

drop function if exists public.match_documents (vector, float, int);
drop function if exists public.match_documents (vector, float, int, uuid);
drop table if exists public.documents;

create table public.documents
(
    id         bigint generated by default as identity not null,
    user_id    uuid                                    not null references auth.users on delete cascade,
    file_name  text                                    not null,
    content    text                                    not null,
    embedding  vector (1536)                           not null,
    created_at timestamp with time zone                not null default now(),
    primary key (id)
);

-- Approximate nearest-neighbour index for fast cosine similarity search.
create index documents_embedding_idx
    on public.documents using hnsw (embedding vector_cosine_ops);

-- Help the planner pre-filter to the calling user's rows.
create index documents_user_id_idx on public.documents (user_id);
create index documents_user_file_idx on public.documents (user_id, file_name);

alter table public.documents enable row level security;

create
policy "Users can read own documents" on public.documents as PERMISSIVE for
select
    to authenticated using (
    (
    select
    auth.uid ()
    ) = user_id
    );

create
policy "Users can insert own documents" on public.documents as PERMISSIVE for INSERT to authenticated
with
  check (
    (
    select
    auth.uid ()
    ) = user_id
    );

create
policy "Users can delete own documents" on public.documents as PERMISSIVE for DELETE to authenticated using (
    (
    select
    auth.uid ()
    ) = user_id
    );

-- Similarity search scoped to a single user's documents. SECURITY INVOKER
-- (the default) means the documents RLS policies above also apply, so a user
-- can never retrieve another user's chunks even if filter_user_id were wrong.
-- Returns file_name so the chat can attribute each excerpt to its source.
-- The extra drop keeps this block runnable on its own: "create or replace"
-- cannot change an existing function's return type.
drop function if exists public.match_documents (vector, float, int, uuid);

create
or replace function match_documents (
  query_embedding vector (1536),
  match_threshold float,
  match_count int,
  filter_user_id uuid
) returns table (id bigint, file_name text, content text, similarity float) language sql stable as $$
select documents.id,
       documents.file_name,
       documents.content,
       1 - (documents.embedding <=> query_embedding) as similarity
from documents
where documents.user_id = filter_user_id
  and 1 - (documents.embedding <=> query_embedding) > match_threshold
order by documents.embedding <=> query_embedding
    limit match_count;
$$;

-- ---------------------------------------------------------------------------
-- Private Storage bucket for user files + per-user folder access policies.
-- The first path segment of every object name must equal the user's id.
-- ---------------------------------------------------------------------------

-- Private bucket. Force public = false even if it already exists, otherwise a
-- pre-existing public bucket would serve every user's files over public URLs,
-- bypassing the object policies below.
insert into storage.buckets (id, name, public)
values ('documents', 'documents', false)
on conflict (id) do update set public = false;

-- storage.objects is a shared system table (not dropped/recreated above), so
-- make these policies re-runnable.
drop policy if exists "Users can read own files" on storage.objects;
drop policy if exists "Users can upload own files" on storage.objects;
drop policy if exists "Users can update own files" on storage.objects;
drop policy if exists "Users can delete own files" on storage.objects;

create
policy "Users can read own files" on storage.objects as PERMISSIVE for
select
    to authenticated using (
    bucket_id = 'documents'
    and (storage.foldername (name)) [1] = (
    select
    auth.uid ()
    ) :: text
    );

create
policy "Users can upload own files" on storage.objects as PERMISSIVE for INSERT to authenticated
with
  check (
    bucket_id = 'documents'
    and (storage.foldername (name)) [1] = (
    select
    auth.uid ()
    ) :: text
    );

create
policy "Users can update own files" on storage.objects as PERMISSIVE for
UPDATE to authenticated using (
    bucket_id = 'documents'
    and (storage.foldername (name)) [1] = (
    select
    auth.uid ()
    ) :: text
    );

create
policy "Users can delete own files" on storage.objects as PERMISSIVE for DELETE to authenticated using (
    bucket_id = 'documents'
    and (storage.foldername (name)) [1] = (
    select
    auth.uid ()
    ) :: text
    );

-- ---------------------------------------------------------------------------
-- Chats + messages (unchanged structure; RLS scopes rows to their owner).
-- ---------------------------------------------------------------------------

drop table if exists public.messages;
drop table if exists public.chats;

create table public.chats
(
    id         uuid primary key                  default gen_random_uuid() not null,
    user_id    uuid                     not null references auth.users on delete cascade,
    title      text                     not null,
    created_at timestamp with time zone not null default now()
);

alter table public.chats ENABLE row LEVEL SECURITY;

create
policy "Enable insert for users based on user_id" on public.chats as PERMISSIVE for INSERT to authenticated
with
  check (
    (
    select
    auth.uid ()
    ) = user_id
    );

create
policy "Enable select for users based on user_id" on public.chats as PERMISSIVE for
select
    to authenticated using (
    (
    select
    auth.uid ()
    ) = user_id
    );

create table public.messages
(
    id         uuid primary key                                      default gen_random_uuid() not null,
    chat_id    uuid references chats (id) on delete cascade not null,
    user_id    uuid                                         not null references auth.users on delete cascade,
    role       text check (role in ('user', 'assistant'))   not null,
    content    text                                         not null,
    created_at timestamp with time zone                     not null default now()
);

alter table public.messages ENABLE row LEVEL SECURITY;

-- The caller may only insert their own messages, and only into a chat they own.
-- RLS is the real boundary here: the browser holds the anon key and can call
-- PostgREST directly, so we must not trust the edge function to scope writes.
create
policy "Enable insert for users based on user_id" on public.messages as PERMISSIVE for INSERT to authenticated
with
  check (
    (
    select
    auth.uid ()
    ) = user_id
    and exists (
    select
    1
    from public.chats c
    where c.id = chat_id
    and c.user_id = (
    select
    auth.uid ()
    )
    )
    );

create
policy "Enable select for users based on user_id" on public.messages as PERMISSIVE for
select
    to authenticated using (
    (
    select
    auth.uid ()
    ) = user_id
    );

-- Persist a full turn (create the chat on first message, then both messages)
-- atomically in one transaction. SECURITY INVOKER keeps the RLS policies above
-- in force, and clock_timestamp() gives the two messages distinct, ordered
-- created_at values so history is always read back in the right order.
create
or replace function public.save_turn (
  p_chat_id uuid,
  p_title text,
  p_user_content text,
  p_assistant_content text
) returns uuid language plpgsql security invoker as $$
declare
  v_uid uuid := auth.uid();
  v_chat_id uuid := p_chat_id;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  if v_chat_id is null then
    insert into public.chats (user_id, title)
    values (v_uid, p_title)
    returning id into v_chat_id;
  elsif not exists (
    select 1 from public.chats c where c.id = v_chat_id and c.user_id = v_uid
  ) then
    raise exception 'Chat not found';
  end if;

  insert into public.messages (chat_id, user_id, role, content, created_at)
  values (v_chat_id, v_uid, 'user', p_user_content, clock_timestamp());

  insert into public.messages (chat_id, user_id, role, content, created_at)
  values (v_chat_id, v_uid, 'assistant', p_assistant_content, clock_timestamp());

  return v_chat_id;
end;
$$;
